#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

cd target && ../bin/spread -v google:ubuntu-18.04-64: google:ubuntu-core-18-64: google:amazon-linux-2-64:
