#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

cd target && ../bin/spread -v google:ubuntu-16.04-64:tests/ google:ubuntu-core-16-64:tests/ google:fedora-28-64:tests/
