#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/sergiocazzolato/validator

. ./options

export UBUNTU_CORE_CHANNEL=edge

cp -rf validator/tests target
cd target
../bin/spread -v google:ubuntu-18.04-64 google:ubuntu-16.04-64 google:ubuntu-16.04-32 google:ubuntu-14.04-64
